;;; bufferwizard.el --- Buffer wizard  -*- lexical-binding: t; -*-

;; Copyright (C) 2024-2026 James Cherti | https://www.jamescherti.com/contact/

;; Author: James Cherti <https://www.jamescherti.com/contact/>
;; Version: 1.0.0
;; URL: https://github.com/jamescherti/bufferwizard.el
;; Keywords: convenience
;; Package-Requires: ((emacs "26.1"))
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:
;; The **bufferwizard** Emacs package provides a collection of helper functions
;; and commands for managing buffers.

;;; Code:

(defgroup bufferwizard nil
  "Buffer wizard settings and configuration."
  :group 'bufferwizard
  :prefix "bufferwizard-"
  :link '(url-link
          :tag "Github"
          "https://github.com/jamescherti/bufferwizard.el"))

;;; Helper functions

(defun bufferwizard--message (&rest args)
  "Display a message with [bufferwizard] prepended.
The message is formatted with the provided arguments ARGS."
  (apply #'message (concat "[bufferwizard] " (car args)) (cdr args)))

(defun bufferwizard--get-list-buffers (filename)
  "Return a list of buffers visiting the specified FILENAME.

FILENAME is the absolute path of the file to check for associated buffers.

Iterates through all buffers and performs the following check: If a buffer is
visiting the specified FILENAME (based on the true file path), it is added to
the resulting list.

Returns a list of buffers that are associated with FILENAME."
  (let ((true-filename (file-truename filename))
        (list-buffers nil))
    (dolist (buf (buffer-list))
      (when (buffer-live-p buf)
        (let* ((base-buf (or (buffer-base-buffer buf) buf))
               (buf-filename (when base-buf (buffer-file-name base-buf))))
          (when (and buf-filename
                     (string-equal true-filename (file-truename buf-filename)))
            (push buf list-buffers)))))
    list-buffers))

;;; Indirect buffers

(defun bufferwizard-clone-indirect-buffer (&optional newname
                                                     display-flag
                                                     norecord)
  "Create an indirect buffer while preserving window state.

This function is an enhanced version of the built-in `clone-indirect-buffer'.

This function creates an indirect buffer with the same content as the current
buffer, ensuring that the point position, window start, and horizontal scroll
position remain unchanged. The original buffer remains intact.

- If NEWNAME is provided, it is used as the name of the new buffer. Otherwise, a
  default name is generated by appending <N> to the current buffer name, where
  N is an incrementing number.
- If DISPLAY-FLAG is non-nil, the new buffer is displayed using `pop-to-buffer'.
  This always happens when called interactively.
- If NORECORD is non-nil, the new buffer is not placed at the front of the
  recently selected buffer list.

This function does not allow cloning buffers whose major mode has a non-nil
`no-clone-indirect' property. If attempted, an error is signaled.

Returns the newly created indirect buffer."
  (interactive
   (progn
     (if (get major-mode 'no-clone-indirect)
         (error "Cannot indirectly clone a buffer in %s mode" major-mode))
     (list (if current-prefix-arg
               (read-buffer "Name of indirect buffer: " (buffer-name)))
           t)))
  (let* ((point-pos (point))
         (previous-window (selected-window))
         (buffer (current-buffer))
         (buffer-in-current-window (eq buffer (window-buffer previous-window)))
         (window-start (when buffer-in-current-window
                         (window-start previous-window)))
         (window-hscroll (when buffer-in-current-window
                           (window-hscroll previous-window)))
         (indirect-buffer (clone-indirect-buffer newname display-flag norecord)))
    (when (buffer-live-p indirect-buffer)
      (switch-to-buffer indirect-buffer)
      (with-current-buffer indirect-buffer
        (goto-char point-pos)
        (let ((current-window (selected-window)))
          ;; Check if the current window is actually displaying the new buffer
          (when (and (window-live-p current-window)
                     (eq (window-buffer current-window) indirect-buffer))
            (when window-start
              (set-window-start current-window window-start t))
            (when window-hscroll
              (set-window-hscroll current-window window-hscroll))))))
    indirect-buffer))

(defun bufferwizard-clone-and-switch-to-indirect-buffer (&optional newname
                                                                   norecord)
  "Create an indirect buffer and switch to it.

This function is a variant of `bufferwizard-clone-indirect-buffer', except it
also switches to the new indirect buffer.

This function creates a new indirect buffer with the same content as the current
buffer, preserving point position, window start, and horizontal scroll position.
The original buffer remains unchanged.

The optional argument NEWNAME specifies the indirect buffer name. If NEWNAME is
nil, the name defaults to the current buffer's name with a <N> suffix added,
or by incrementing N in an existing suffix. An error occurs when attempting to
clone a buffer whose major mode symbol has a non-nil `no-clone-indirect'
property.

The optional argument NORECORD, when non-nil, prevents putting this buffer at
the front of the list of recently selected ones.

Returns the newly created indirect buffer."
  (interactive
   (progn
     (if (get major-mode 'no-clone-indirect)
         (error "Cannot indirectly clone a buffer in %s mode" major-mode))
     (list (if current-prefix-arg
               (read-buffer "Name of indirect buffer: " (buffer-name)))
           t)))
  (bufferwizard-clone-indirect-buffer newname nil norecord))

(defun bufferwizard-switch-to-base-buffer (&optional buffer)
  "Switch to the base buffer if BUFFER is indirect.
Preserve point, `window-start', and horizontal scrolling."
  (interactive)
  (let* ((target-buf (or buffer (current-buffer)))
         (base-buffer (buffer-base-buffer target-buf)))
    (unless base-buffer
      (user-error "Buffer '%s' is not an indirect buffer"
                  (buffer-name target-buf)))
    (let* ((point-pos (with-current-buffer target-buf (point)))
           (current-buf (current-buffer))
           (window (selected-window))
           (buffer-in-current-window (eq current-buf (window-buffer window)))
           (window-start (when buffer-in-current-window
                           (window-start window)))
           (window-hscroll (when buffer-in-current-window
                             (window-hscroll window))))
      (switch-to-buffer base-buffer)
      (goto-char point-pos)
      ;; Use the active window after the switch, not necessarily the old one
      (let ((new-window (selected-window)))
        (when (and (window-live-p new-window)
                   (eq (window-buffer new-window) base-buffer))
          (when window-start
            (set-window-start new-window window-start t))
          (when window-hscroll
            (set-window-hscroll new-window window-hscroll)))))))

;;; Search and replace (string)

(defun bufferwizard-replace-regexp (from-regexp &optional to-string)
  "Replace occurrences of FROM-REGEXP with TO-STRING.
When TO-STRING is not specified, the user is prompted for input.
This function confirms each replacement."
  (when buffer-read-only
    (error "The buffer '%s' is read-only" (buffer-name)))
  (unless to-string
    (setq to-string (read-string (format "Replace '%s' with: " from-regexp))))
  (let* ((buf (current-buffer))
         (window (selected-window))
         (buffer-in-current-window (eq buf (window-buffer window)))
         (orig-window-start (when buffer-in-current-window
                              (window-start window)))
         (scroll-conservatively 10)
         (search-invisible t))
    (save-excursion
      (let ((start (point)))
        (unwind-protect
            (with-undo-amalgamate
              ;; Replace from the current position
              (query-replace-regexp from-regexp to-string nil start (point-max))

              ;; Replace from the beginning
              (when (> start (point-min))
                (query-replace-regexp
                 from-regexp to-string nil (point-min) (1- start))))
          ;; Sound restoration check: Is the window alive and still holding our
          ;; buffer?
          (when (and orig-window-start
                     (window-live-p window)
                     (eq (window-buffer window) buf))
            (set-window-start window orig-window-start t)))))))

(defun bufferwizard--symbol-at-point-regexp ()
  "Return a regexp that matches the symbol at point."
  (when-let* ((symbol (thing-at-point 'symbol t)))
    (when symbol
      (concat "\\_<" (regexp-quote symbol) "\\_>"))))

;;;###autoload
(defun bufferwizard-replace-symbol-at-point (&optional to-string)
  "Replace occurrences of a symbol at point with a specified TO-STRING.
When TO-STRING is not specified, the user is prompted for input.
This function confirms each replacement."
  (interactive)
  (when buffer-read-only
    (error "The buffer '%s' is read-only" (buffer-name)))
  (let ((region (use-region-p))
        from-string string-start string-regexp)
    (if region
        ;; Region
        (progn
          (setq from-string (buffer-substring-no-properties (region-beginning)
                                                            (region-end)))
          (setq string-start (region-beginning))
          (deactivate-mark)
          (setq string-regexp (regexp-quote from-string)))
      ;; Not a region. Use the symbol at point.
      (setq from-string (thing-at-point 'symbol t))
      (when from-string
        (setq string-start (car (bounds-of-thing-at-point 'symbol)))
        (setq string-regexp (bufferwizard--symbol-at-point-regexp))))

    (when from-string
      ;; Only apply visual highlighting if we need to prompt the user
      (unless to-string
        (let ((highlighted-regexp string-regexp))
          (unwind-protect
              (progn
                (highlight-regexp highlighted-regexp 'lazy-highlight)
                (setq to-string
                      (read-string (format "Replace '%s' with: " from-string)
                                   from-string)))
            (unhighlight-regexp highlighted-regexp))))

      ;; Replace
      (goto-char string-start)
      (let (;; This fixes issues with packages such as aggressive-indent by
            ;; temporarily preventing automatic buffer modifications during the
            ;; replacement. Without this, asynchronous changes (like
            ;; auto-indentation) can shift point and markers, causing replacements
            ;; to affect the wrong text.
            (inhibit-modification-hooks t))
        (bufferwizard-replace-regexp string-regexp to-string)))))

;;; Highlight symbols

(defun bufferwizard-get-symbol-or-region-regexp ()
  "Return the regexp of the selected region or the default symbol at point."
  (if (use-region-p)
      (regexp-quote (buffer-substring-no-properties (region-beginning)
                                                    (region-end)))
    (find-tag-default-as-symbol-regexp)))

(defun bufferwizard-highlight-p ()
  "Return non-nil if the symbol at point is currently highlighted."
  (require 'hi-lock)
  (when (fboundp 'hi-lock--regexps-at-point)
    (when-let* ((regexp (bufferwizard-get-symbol-or-region-regexp)))
      (member regexp (hi-lock--regexps-at-point)))))

;;;###autoload
(defun bufferwizard-highlight-at-point ()
  "Highlight the symbol at point in the current buffer.

This function identifies the symbol at the current point, generates the
appropriate regular expression for it, and applies highlighting using the
built-in `hi-lock' package."
  (interactive)
  (require 'hi-lock)
  (when (and (fboundp 'hi-lock-read-face-name)
             (fboundp 'hi-lock-mode)
             (fboundp 'hi-lock-set-pattern))
    ;; Similar to `hi-lock-face-symbol-at-point'
    (let* ((regexp (bufferwizard-get-symbol-or-region-regexp))
           (hi-lock-auto-select-face t)
           (face (hi-lock-read-face-name)))
      (ignore hi-lock-auto-select-face)
      (when regexp
        (or (facep face) (setq face 'hi-yellow))
        (unless (bound-and-true-p hi-lock-mode)
          (hi-lock-mode 1))
        (hi-lock-set-pattern
         regexp face nil nil
         (if (and case-fold-search search-upper-case)
             (isearch-no-upper-case-p regexp t)
           case-fold-search))))))

;;;###autoload
(defun bufferwizard-unhighlight-at-point ()
  "Remove highlighting for the symbol at point."
  (interactive)
  (require 'hi-lock)
  (when (fboundp 'hi-lock-unface-buffer)
    (when-let* ((regexp (bufferwizard-get-symbol-or-region-regexp)))
      (hi-lock-unface-buffer regexp))))

;;;###autoload
(defun bufferwizard-toggle-highlight-at-point ()
  "Toggle highlighting for the symbol at point.

This function checks if the symbol at point is currently highlighted.
If it is, it removes the highlight; otherwise, it applies the highlight."
  (interactive)
  (if (bufferwizard-highlight-p)
      (bufferwizard-unhighlight-at-point)
    (bufferwizard-highlight-at-point)))

;;;###autoload
(defun bufferwizard-unhighlight ()
  "Remove highlighting of each match to REGEXP.
Interactively, prompt for REGEXP, accepting only regexps previously inserted by
hi-lock interactive functions. If REGEXP is t (or if \\[universal-argument] was
specified interactively), then remove all hi-lock highlighting."
  (interactive)
  (require 'hi-lock)
  (when (fboundp 'hi-lock-unface-buffer)
    (call-interactively #'hi-lock-unface-buffer)))

;;; Highlight TODO code tags

(defcustom bufferwizard-hl-todo-keywords
  '(("TODO"   . font-lock-warning-face)
    ("FIXME"  . font-lock-warning-face)
    ("BUG"    . font-lock-warning-face)
    ("XXX"    . font-lock-warning-face)
    ("DONE"   . font-lock-doc-face)
    ("HACK"   . font-lock-doc-face)
    ("NOTE"   . font-lock-doc-face))
  "Alist of keywords to highlight and their corresponding colors or faces.
Each element is a cons cell: (KEYWORD . COLOR-OR-FACE).
- KEYWORD is a string representing the tag (e.g., \"TODO\").
- COLOR-OR-FACE is either a string specifying a hex color (e.g., \"#FF0000\")
or a symbol representing an existing face (e.g., \\='font-lock-warning-face)."
  :type '(alist :key-type string
                :value-type
                (choice (color :tag "Hex Color (e.g., ##FF0000)")
                        (face :tag "Face Name (e.g., font-lock-doc-face)")))
  :group 'bufferwizard)

(defvar bufferwizard--compiled-hl-todo-keywords nil
  "Internal cache of compiled font-lock keywords for highlighting TODOs.")

(defun bufferwizard--compile-hl-todo-keywords ()
  "Translate `bufferwizard-hl-todo-keywords' into optimized `font-lock' regexps."
  (require 'seq)
  (if (fboundp 'seq-group-by)
      (let* (;; Group the alist by the cdr (the face/color)
             ;; Result:
             ;; '((font-lock-warning-face . (("TODO" . face)
             ;;                              ("FIXME" . face))) ...)
             (grouped-by-face (seq-group-by #'cdr bufferwizard-hl-todo-keywords))
             compiled-rules)

        (dolist (group grouped-by-face)
          (let* ((color-or-face (car group))  ; This group's face/color
                 (entries (cdr group))        ; The list of matching cons cells
                 (keywords (mapcar #'car entries)) ; Extract string keywords

                 ;; regexp-opt safely escapes and builds the fastest possible
                 ;; OR-regexp
                 (regexp (concat "\\_<\\(" (regexp-opt keywords) "\\)\\_>"))

                 ;; Dynamically determine the face property
                 (face-prop (if (stringp color-or-face)
                                (list 'quote (list :foreground color-or-face
                                                   :weight 'bold))
                              (list 'quote color-or-face))))

            ;; Add the optimized rule for this face group to our final list
            (push (list regexp 1 face-prop 'prepend) compiled-rules)))

        compiled-rules)
    (error "Undefined: seq-group-by")))

;;;###autoload
(define-minor-mode bufferwizard-hl-todo-local-mode
  "Minor mode to highlight keywords like TODO, FIXME, etc.

When enabled, this mode dynamically builds font-lock rules from
the key-value pairs defined in `bufferwizard-hl-todo-keywords'."
  :global nil
  :lighter " bw-todo"
  :group 'bufferwizard
  (if bufferwizard-hl-todo-local-mode
      (progn
        ;; Compile and store the keywords so we can reliably remove them later
        (setq bufferwizard--compiled-hl-todo-keywords
              (bufferwizard--compile-hl-todo-keywords))
        (font-lock-add-keywords nil bufferwizard--compiled-hl-todo-keywords t))
    ;; Remove the exact keywords we previously added
    (font-lock-remove-keywords nil bufferwizard--compiled-hl-todo-keywords))

  ;; Refresh font-lock to apply/remove changes immediately
  (when (bound-and-true-p font-lock-mode)
    (if (fboundp 'font-lock-flush)
        (font-lock-flush)
      (with-no-warnings
        (font-lock-fontify-buffer)))))

;;;###autoload
(define-globalized-minor-mode bufferwizard-hl-todo-mode
  bufferwizard-hl-todo-local-mode
  (lambda () (bufferwizard-hl-todo-local-mode 1))
  :group 'bufferwizard)

;;; Provide
(provide 'bufferwizard)

;;; bufferwizard.el ends here
